name: Build and Deploy Storybook
on: ['push']
  # push:
  #   Trigger the action only when files change in the folders defined here
  #   paths: ["src/stories/**", "src/components/**"]
jobs:
  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          npm install
          npm run build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: docs
          clean: true